In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:

pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [53]:
dataset = pd.read_csv('data.csv')

In [54]:
dataset.head(200)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean   
0      842302         M        17.99         10.38          122.80     1001.0  \
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
195    875878         B        12.91         16.33           82.53      516.4   
196    875938         M        13.77         22.29           90.63      588.9   
197    877159         M        18.08         21.84          117.40     1024.0   
198    877486         M        19.18         22.49          127.50     1148.0   
199    877500         M        14.45         20.22           94.49      642.7   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean   
0            0.11840           0.27760         0.30010              0.14710  \
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
195          0.07941           0.05366         0.03873              0.02377   
196          0.12000           0.12670         0.13850              0.06526   
197          0.07371           0.08642         0.11030              0.05778   
198          0.08523           0.14280         0.11140              0.06772   
199          0.09872           0.12060         0.11800              0.05980   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst   
0    ...          17.33           184.60      2019.0           0.16220  \
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
195  ...          22.00            90.81       600.6           0.10970   
196  ...          34.01           111.60       806.9           0.17370   
197  ...          24.70           129.10      1228.0           0.08822   
198  ...          32.06           166.40      1688.0           0.13220   
199  ...          30.12           117.90      1044.0           0.15520   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst   
0               0.6656           0.7119               0.26540          0.4601  \
1               0.1866           0.2416               0.18600          0.2750   
2               0.4245           0.4504               0.24300          0.3613   
3               0.8663           0.6869               0.25750          0.6638   
4               0.2050           0.4000               0.16250          0.2364   
..                 ...              ...                   ...             ...   
195             0.1506           0.1764               0.08235          0.3024   
196             0.3122           0.3809               0.16730          0.3080   
197             0.1963           0.2535               0.09181          0.2369   
198             0.5601           0.3865               0.17080          0.3193   
199             0.4056           0.4967               0.18380          0.4753   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [67]:
list(dataset)

['id',
 'diagnosis',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst',
 'Unnamed: 32']

In [69]:
# 

Y = dataset.iloc[:, 1:31].values
X = dataset.iloc[:,31].values

In [70]:
X

array([0.1189 , 0.08902, 0.08758, 0.173  , 0.07678, 0.1244 , 0.08368,
       0.1151 , 0.1072 , 0.2075 , 0.08452, 0.1048 , 0.1023 , 0.06287,
       0.1431 , 0.1341 , 0.08216, 0.1142 , 0.07615, 0.07259, 0.08183,
       0.07773, 0.09946, 0.07526, 0.09564, 0.1059 , 0.1275 , 0.07421,
       0.09876, 0.07919, 0.09782, 0.1402 , 0.08482, 0.1123 , 0.1233 ,
       0.08633, 0.1014 , 0.06169, 0.05504, 0.1071 , 0.07146, 0.09606,
       0.1038 , 0.1027 , 0.09618, 0.09185, 0.07409, 0.1179 , 0.08301,
       0.06917, 0.06563, 0.08025, 0.07408, 0.07987, 0.07873, 0.07036,
       0.08294, 0.1094 , 0.06289, 0.09026, 0.0802 , 0.07712, 0.1132 ,
       0.0849 , 0.1031 , 0.08911, 0.09211, 0.06641, 0.1175 , 0.0641 ,
       0.06589, 0.1084 , 0.1339 , 0.103  , 0.07609, 0.06387, 0.07191,
       0.1108 , 0.09964, 0.07918, 0.08851, 0.1016 , 0.1051 , 0.09203,
       0.07924, 0.08579, 0.06846, 0.09288, 0.09261, 0.08473, 0.07246,
       0.06828, 0.06206, 0.06603, 0.08234, 0.08368, 0.07376, 0.08988,
       0.08756, 0.09

In [71]:
Y

array([[ 1.    , 17.99  , 10.38  , ...,  0.7119,  0.2654,  0.4601],
       [ 1.    , 20.57  , 17.77  , ...,  0.2416,  0.186 ,  0.275 ],
       [ 1.    , 19.69  , 21.25  , ...,  0.4504,  0.243 ,  0.3613],
       ...,
       [ 1.    , 16.6   , 28.08  , ...,  0.3403,  0.1418,  0.2218],
       [ 1.    , 20.6   , 29.33  , ...,  0.9387,  0.265 ,  0.4087],
       [ 0.    ,  7.76  , 24.54  , ...,  0.    ,  0.    ,  0.2871]])

In [59]:
dataset.shape

(569, 33)

In [60]:
dataset.value_counts("diagnosis")

diagnosis
B    357
M    212
Name: count, dtype: int64

In [34]:
dataset.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [35]:
dataset.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [72]:
# Encoding Categorical data values
import sklearn
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X = labelencoder_X.fit_transform(X)

# data = pd.get_dummies(new_data["diagnosis"])
# new_data = pd.concat([new_data["diagnosis"]])


In [64]:
new_data["diagnosis"].replace({'M':1, 'B':0}, inplace=True)

In [73]:
new_data.head(20)

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean   
0     842302          1        17.99         10.38          122.80     1001.0  \
1     842517          1        20.57         17.77          132.90     1326.0   
2   84300903          1        19.69         21.25          130.00     1203.0   
3   84348301          1        11.42         20.38           77.58      386.1   
4   84358402          1        20.29         14.34          135.10     1297.0   
5     843786          1        12.45         15.70           82.57      477.1   
6     844359          1        18.25         19.98          119.60     1040.0   
7   84458202          1        13.71         20.83           90.20      577.9   
8     844981          1        13.00         21.82           87.50      519.8   
9   84501001          1        12.46         24.04           83.97      475.9   
10    845636          1        16.02         23.24          102.70      797.8   
11  84610002          1        15.78         17.89          103.60      781.0   
12    846226          1        19.17         24.80          132.40     1123.0   
13    846381          1        15.85         23.95          103.70      782.7   
14  84667401          1        13.73         22.61           93.60      578.3   
15  84799002          1        14.54         27.54           96.73      658.8   
16    848406          1        14.68         20.13           94.74      684.5   
17  84862001          1        16.13         20.68          108.10      798.8   
18    849014          1        19.81         22.15          130.00     1260.0   
19   8510426          0        13.54         14.36           87.46      566.3   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean   
0           0.11840           0.27760         0.30010              0.14710  \
1           0.08474           0.07864         0.08690              0.07017   
2           0.10960           0.15990         0.19740              0.12790   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.12780           0.17000         0.15780              0.08089   
6           0.09463           0.10900         0.11270              0.07400   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.09740           0.24580         0.20650              0.11180   
13          0.08401           0.10020         0.09938              0.05364   
14          0.11310           0.22930         0.21280              0.08025   
15          0.11390           0.15950         0.16390              0.07364   
16          0.09867           0.07200         0.07395              0.05259   
17          0.11700           0.20220         0.17220              0.10280   
18          0.09831           0.10270         0.14790              0.09498   
19          0.09779           0.08129         0.06664              0.04781   

    ...  texture_worst  perimeter_worst  area_worst  smoothness_worst   
0   ...          17.33           184.60      2019.0            0.1622  \
1   ...          23.41           158.80      1956.0            0.1238   
2   ...          25.53           152.50      1709.0            0.1444   
3   ...          26.50            98.87       567.7            0.2098   
4   ...          16.67           152.20      1575.0            0.1374   
5   ...          23.75           103.40       741.6            0.1791   
6   ...          27.66           153.20      1606.0            0.1442   
7   ...          28.14           110.60       897.0            0.1654   
8   ...     

In [74]:
Y

array([[ 1.    , 17.99  , 10.38  , ...,  0.7119,  0.2654,  0.4601],
       [ 1.    , 20.57  , 17.77  , ...,  0.2416,  0.186 ,  0.275 ],
       [ 1.    , 19.69  , 21.25  , ...,  0.4504,  0.243 ,  0.3613],
       ...,
       [ 1.    , 16.6   , 28.08  , ...,  0.3403,  0.1418,  0.2218],
       [ 1.    , 20.6   , 29.33  , ...,  0.9387,  0.265 ,  0.4087],
       [ 0.    ,  7.76  , 24.54  , ...,  0.    ,  0.    ,  0.2871]])

In [77]:
# Spliiting the dataset into the training set and test set\

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Y,X, test_size = 0.25, random_state = 0)

In [44]:
# dataset['diagnosis'] = dataset['diagnosis'].map({'M': 1, 'B': 0})

In [27]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [28]:
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean   
0    842302         M        17.99         10.38          122.80     1001.0  \
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean   
0          0.11840           0.27760          0.3001              0.14710  \
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst   
0  ...          17.33           184.60      2019.0            0.1622  \
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst   
0             0.6656           0.7119                0.2654          0.4601  \
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [78]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [96]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, Y_train)

# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
# classifier.fit(X_train, Y_train)

C:\Users\shubhammas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [100]:
# score = classifier.score(X_test, Y_test)
# print(score)


In [92]:
Y_pred = classifier.predict(X_test)
Y_pred

array([465,  41,   3,  29,  39, 128, 135,  96, 110, 160, 235,  34, 200,
        34, 217, 264, 356,  70, 175, 189, 478, 309, 177, 198, 189,  75,
        15, 483, 104, 312,  55,  10, 219, 272,  35, 376,  47,  10,  21,
       195,  41, 169,  48,  35, 269, 229,  35,  59, 111, 444, 398, 309,
        70,  65, 123,  79,   5,   8,  61, 156, 461, 146,  12,  96, 229,
        41, 362, 188,  28, 168, 217, 304,  75,  89, 237,  41, 225, 192,
         1,  72,  51, 461, 336,  12, 251,  47,  15, 168, 272, 362,  79,
       264, 100, 444,  49, 165, 229, 326, 260, 128, 366, 163,   3, 105,
        35, 379, 336, 177,  48, 113, 128, 201, 272, 109, 128,  67,  76,
        45,  67,  76,  12,  37, 448, 177, 257, 337,  47, 101, 298,  22,
        35,  35,  81, 394, 425,  84,  41,  48, 202, 290, 163, 186, 189],
      dtype=int64)

In [90]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)
c = print(cm[0,0]+ cm[1,1])

0
